var results2011 = '' +  
'<DIV class=subtitle>2011 Dragon Boat Race Results</DIV>' + 
'<SPAN class=subtitle2>Festival Grand Champion</SPAN> Still Floatin - Irving Fire Department<BR>' + 
'<DIV class=subtitle2>Festival Grand Championship Race (Mixed Teams)</DIV>' + 
'<SPAN class=subtitle1>1<sup>st</sup> Place</SPAN> AC<BR>' + 
'<SPAN class=subtitle1>2<sup>nd</sup> Place</SPAN> Cajun Invasion<BR>' + 
'<SPAN class=subtitle1>3<sup>rd</sup> Place</SPAN> Hustle and Float<BR>' + 
'<DIV class=subtitle2>Youth Division - Mixed</DIV>' + 
'<SPAN class=subtitle1>1<sup>st</sup> Place</SPAN> FCC Youth - Family with Children from China<BR>' + 
'<DIV class=subtitle2>Youth Division - Men\'s </DIV>' + 
'<SPAN class=subtitle1>1<sup>st</sup> Place</SPAN> Circle Ten Swamp Rats - Boy Scouts<BR>' + 
'<DIV class=subtitle2>Corporate Blue Bonnet Division</DIV>' + 
'<SPAN class=subtitle1>1<sup>st</sup> Place</SPAN> Huawei #1<BR>' + 
'<SPAN class=subtitle1>2<sup>nd</sup> Place</SPAN> DragonSlayers #2<BR>' + 
'<SPAN class=subtitle1>3<sup>rd</sup> Place</SPAN> Ernst & Young LLP<BR>' + 
'<DIV class=subtitle2>Corporate Wildflower Division</DIV>' + 
'<SPAN class=subtitle1>1<sup>st</sup> Place</SPAN> Team Samsung, Samsung<BR>' + 
'<SPAN class=subtitle1>2<sup>nd</sup> Place</SPAN> MIK Power Dragons, Michaels Stores, Inc.<BR>' + 
'<SPAN class=subtitle1>3<sup>rd</sup> Place</SPAN> Paddle Happy, AT&T<BR>' + 
'<DIV class=subtitle2>Cancer Awareness Division</DIV>' + 
'<SPAN class=subtitle1>1<sup>st</sup> Place</SPAN> Cajun Invasion, Team from Louisiana and Houston<BR>' + 
'<SPAN class=subtitle1>2<sup>nd</sup> Place</SPAN> Mudzillas, Community team<BR>' + 
'<SPAN class=subtitle1>3<sup>rd</sup> Place</SPAN> NAAAP Dragon, NAAAP-DFW<BR>' + 
'<DIV class=subtitle2>Community Lantana Division</DIV>' + 
'<SPAN class=subtitle1>1<sup>st</sup> Place</SPAN> Hustle & Float<BR>' + 
'<SPAN class=subtitle1>2<sup>nd</sup> Place</SPAN> AC<BR>' + 
'<SPAN class=subtitle1>3<sup>rd</sup> Place</SPAN> Dallas Dream Rowers<BR>' + 
'<DIV class=subtitle2>Community Sunflower Division</DIV>' + 
'<SPAN class=subtitle1>1<sup>st</sup> Place</SPAN> That’s How We Row<BR>' + 
'<SPAN class=subtitle1>2<sup>nd</sup> Place</SPAN> Sea Esta<BR>' + 
'<SPAN class=subtitle1>3<sup>rd</sup> Place</SPAN> Sister Cities Two: Greater Irving-Las Colinas<BR>Chamber of Commerce<BR>' + 
'<DIV class=subtitle2>Open Division</DIV>' +
'<SPAN class=subtitle1>1<sup>st</sup> Place</SPAN> Five-O, Irving Police Department<BR>' + 
'<SPAN class=subtitle1>2<sup>nd</sup> Place</SPAN> Energence<BR>' + 
'<SPAN class=subtitle1>3<sup>rd</sup> Place</SPAN> Dallas Sheriff’s Dept<BR><BR>' + 
'<DIV class=subtitle2>Community Men\'s Division</DIV>' + 
'<SPAN class=subtitle1>1<sup>st</sup> Place</SPAN> HLao-Thai Nam<BR>' + 
'<SPAN class=subtitle1>2<sup>nd</sup> Place</SPAN> Wave Riders<BR>' + 
'<SPAN class=subtitle1>3<sup>rd</sup> Place</SPAN> Power Dragons<BR>' + 
'<DIV class=subtitle2>Men\'s Premier Division</DIV>' + 
'<SPAN class=subtitle1>1<sup>st</sup> Place</SPAN> Still Floatin, Irving Fire Department<BR>' + 
'<SPAN class=subtitle1>2<sup>nd</sup> Place</SPAN> Austin Coolers, Team from Austin<BR>' + 
'<SPAN class=subtitle1>3<sup>rd</sup> Place</SPAN> KOI, Community team<BR>'; 
