var release2007 = '' + 
'<DIV class=subtitle style="text-align: center;">ONE OF HOTTEST WATER SPORTS IS COMING TO DFW<BR>APRIL 29, 2007 AT LAKE CAROLYN, IRVING, TX</DIV>' + 
'<P class=subtitle2 style="text-align: center;">Festival is free to the public</P>' + 
'<P><B>Irving &#151; April 12, 2007</B> - DFW has never witnessed it before, but Dragon Boat racing, a 2,000 year-old Chinese team sport and one of the hottest and fastest growing water sports, is coming to DFW on April 29, 2007 at Lake Carolyn, Irving, Texas. The 1st Annual DFW Dragon Boat, Kite and Lantern Festival is taking place at a fitting juncture in time, as the DFW region grows more international each year.</P>' + 
'<P>In other cities across Texas, California, and New York and countries such as Canada, Singapore and Australia, thousands gather to cheer their favorite dragon boat teams. In China, Hong Kong and Taiwan, this is a must attend festival each May. With Asian Pacific Heritage Month coming in May, area Mayors will read proclamations to salute the achievements and contributions by Asian Pacific Americans in this nation.</P>' + 
'<P>It will be a day of fun and learning starting with lessons on kite flying at 8 AM. Opening ceremonies will begin at 10 AM highlighted by an authentic dragon dance, swirling it’s magic. Dragon Boat Racing will then begin under the oversight and assistance of the Texas Dragon Boat Association. In addition, there will be ethnic foods to sample, handicrafts as well as cultural demonstrations to enjoy, and a wide variety of cultural entertainment to watch. Prizes for the races will be awarded in the evening ending with a Parade of Nations in the Lantern Festival.</P>' + 
'<P>The Dallas County Affiliate of Susan G. Komen for the Cure® is sponsoring a special race dedicated to breast cancer awareness. More and more women are not only surviving, but they are also finding great strength and renewal in a sport they would have never dreamt of trying before. This is co-sponsored by the Irving International Women’s Consortium.</P>' + 
'<P>The event is organized by the Marco Polo World Foundation and is supported by community non-profit organizations such as ACP Foundation, public entities such as DART and DFW Airport, and corporations including CITI, Raytheon, KERA and a number of Asian Chambers of Commerce. It has received much encouragement from the Irving city Mayor, the First Lady, Visitor’s Bureau and the Irving/Las Colinas Chamber of Commerce.</P>' + 
'<P>The goal of the festival is to be all-inclusive, inviting all communities, cities and business groups to join in to celebrate and grow this educational and cultural regional festival. For more information, see www.dfwDragonBoatFestival.com</P>'; 
