var release2009 = '' + 
'<DIV class=subtitle style="text-align: center;">Marco Polo World Foundation Announces 2009 Annual DFW Dragon Boat, Kite, and Lantern Festival to be held May 17th, 2009</DIV>' + 
'<P>IRVING, TX- (April 27, 2009) - Marco Polo World Foundation today announced the 2009 Annual DFW Dragon Boat, Kite, and Lantern Festival will be held on May 17th, 2009. The annual festival will take place from 10:00 a.m. to 6:00 p.m. at Lake Carolyn, Irving, Texas.</P>' + 
'' + 
'<P>"Over thirty dragon boat teams will be competing this year for the coveted DFW Grand Championship." said festival co-chairs, Lily Mak, Grace Tyler, and Meilan Wang.  "This year, we are expanding the festival program with more cultural activities and demonstrations."  The festival features colorful displays of Oriental lanterns, spectacular kite-flying, beautiful Asian dance performances, martial arts demonstrations, as well as traditional lion and dragon dances. In addition, a special ceremony and dragon boat race will be dedicated to increase breast cancer awareness. Vendor booths and a variety of food stations will provide international treats.</P>' + 
'<P>The 2009 DFW Dragon Boat, Kite, and Lantern Festival celebrates Asian/Pacific American Heritage Month and is hosted by the Marco Polo World Foundation, a non-profit organization dedicated to expanding awareness and education of Asian cultures and to promoting the sport of dragon boat racing in North Texas. All festival organizers are volunteers from the community.  Strong support from corporations, community organizations, and the City of Irving has made this festival possible. The event is free to the public at attend.</P>' + 
'<P>Dragon boat racing is one of the fastest-growing sporting events in America. Popular in Asia for centuries, it is relatively new to the western hemisphere. Programs along the east and west coasts of the United States and Canada attract roughly 50,000 participants each year.</P>' + 
'' + 
'<DIV class=subtitle>About Marco Polo World Foundation (MPWF)</DIV>' + 
'<P>Marco Polo World Foundation is a non-profit, volunteer based organization. Its mission is to showcase Asian culture, enhance intercultural understanding and education, celebrate Asian/Pacific American Heritage Month, and promote the sport of dragon boating in the DFW region. Marco Polo World Foundation initiated the first annual DFW Dragon Boat, Kite, and Lantern Festival in 2007. The Foundation works with private and public sector partners and community organizations to encourage regional and international participation.</P>'; 
