var results2008 = '' +  
'<DIV class=subtitle>2008 Dragon Boat Race Results</DIV>' + 
'<SPAN class=subtitle2>Festival Grand Champion</SPAN> Hope We Float - Irving Fire Department<BR>' + 
'<SPAN class=subtitle1>1st Runner Up</SPAN> Lee\'s White Leopard Alpha - Lee\'s White Leopard Kung Fu School<BR>' + 
'<SPAN class=subtitle1>2nd Runner Up</SPAN> USCCC<BR>' + 
'<SPAN class=subtitle1>3rd Runner Up</SPAN> Team OCA &#151; OCA-DFW<BR>' + 
'<DIV class=subtitle2>Youth Division</DIV>' + 
'<SPAN class=subtitle1>1st Place</SPAN> Western Star Boy Scouts<BR>' + 
'<DIV class=subtitle2>Junior Division</DIV>' + 
'<SPAN class=subtitle1>1st Place</SPAN> St. Mark\'s Lions - St. Mark\'s of Texas<BR>' + 
'<DIV class=subtitle2>Inter-City Division</DIV>' + 
'<SPAN class=subtitle1>1st Place</SPAN> Hope We Float - Irving Fire Department<BR>' + 
'<DIV class=subtitle2>Breast Cancer Awareness Division</DIV>' + 
'<SPAN class=subtitle1>1st Place</SPAN> Pure Phun - Houston/Louisiana Team<BR>' + 
'<SPAN class=subtitle1>2nd Place</SPAN> Asian Breast Health Outreach Project - Susan G. Komen Grantee<BR>' + 
'<SPAN class=subtitle1>3rd Place</SPAN> Ms Biz - Ms Biz AM 1110<BR>' + 
'<DIV class=subtitle2>Lawyer\'s Cup Division</DIV>' + 
'<SPAN class=subtitle1>1st Place</SPAN> DAABA Legal Lions - DAABA<BR>' + 
'<SPAN class=subtitle1>2nd Place</SPAN> Litigate Oars - Sidley Austin LLC<BR>' + 
'<DIV class=subtitle2>Community Division</DIV>' + 
'<SPAN class=subtitle1>1st Place</SPAN> Team ACP - ACP Foundation<BR>' + 
'<SPAN class=subtitle1>2nd Place</SPAN> Team OCA &#151; OCA-DFW<BR>' + 
'<SPAN class=subtitle1>3rd Place</SPAN> Jade Dragon - Crow Collection of Asian Art<BR>' + 
'<DIV class=subtitle2>Men\'s Premier Division</DIV>' + 
'<SPAN class=subtitle1>1st Place</SPAN> USCCC<BR>' + 
'<SPAN class=subtitle1>2nd Place</SPAN> Lee\'s White Leopard Alpha - Lee\'s White Leopard Kung Fu School<BR><BR>'; 
