var results2009 = '' +  
'<DIV class=subtitle>2009 Dragon Boat Race Results</DIV>' + 
'<SPAN class=subtitle2>Festival Grand Champion</SPAN> Hope We Float - Irving Fire Department<BR>' + 
'<SPAN class=subtitle1>2<sup>nd</sup> Place</SPAN> Taiwan Formosa of Denton <BR>' + 
'<SPAN class=subtitle1>3<sup>rd</sup> Place</SPAN> Rock-N-Roll, DFW Technology, Inc<BR>' + 
'<SPAN class=subtitle1>4<sup>th</sup> Place</SPAN> Wok n’ Row - Mr. Wok Asian Bistro<BR>' + 
'<DIV class=subtitle2>Youth Division</DIV>' + 
'<SPAN class=subtitle1>1<sup>st</sup> Place</SPAN> Boy Scouts of Circle 10, Boy Scouts of America<BR>' + 
'<DIV class=subtitle2>Community Blue Bonnet Division</DIV>' + 
'<SPAN class=subtitle1>1<sup>st</sup> Place</SPAN> Organization of Chinese Americans (OCA)<BR>' + 
'<SPAN class=subtitle1>2<sup>nd</sup> Place</SPAN> Dallas Asian American Bar Association Legal Lions<BR>' + 
'<SPAN class=subtitle1>3<sup>rd</sup> Place</SPAN> ACP Foundation<BR>' + 
'<SPAN class=subtitle1>4<sup>th</sup> Place</SPAN> Apex-Ascend<BR>' + 
'<SPAN class=subtitle1>5<sup>th</sup> Place</SPAN> Irving Chamber of Commerce<BR>' + 
'<DIV class=subtitle2>Community Wildflower Division</DIV>' + 
'<SPAN class=subtitle1>1<sup>st</sup> Place</SPAN> Power Dragon<BR>' + 
'<SPAN class=subtitle1>2<sup>nd</sup> Place</SPAN> FCC1 (Families with Children from China)<BR>' + 
'<SPAN class=subtitle1>3<sup>rd</sup> Place</SPAN> The Drunken Centipede<BR>' + 
'<SPAN class=subtitle1>4<sup>th</sup> Place</SPAN> Titanic<BR>' + 
'<SPAN class=subtitle1>5<sup>th</sup> Place</SPAN> FCC2 (Families with Children from China)<BR>' + 
'<SPAN class=subtitle1>6<sup>th</sup> Place</SPAN> Blazer Spirit<BR>' + 
'<DIV class=subtitle2>Cancer Awareness Division</DIV>' + 
'<SPAN class=subtitle1>1<sup>st</sup> Place</SPAN> KOI 1 for Asian Breast Health Outreach in memory of Dina Casana<BR>' + 
'<SPAN class=subtitle1>2<sup>nd</sup> Place</SPAN> Mudzilla<BR>' + 
'<SPAN class=subtitle1>3<sup>rd</sup> Place</SPAN> Merit Chinese School for Asian Breast Health Outreach Project<BR>' + 
'<SPAN class=subtitle1>4<sup>th</sup> Place</SPAN> KOI 2 for Asian Breast Health Outreach in memory of Dina Casana<BR>' + 
'<DIV class=subtitle2>Corporate Division</DIV>' + 
'<SPAN class=subtitle1>1<sup>st</sup> Place</SPAN> The Planet<BR>' + 
'<SPAN class=subtitle1>2<sup>nd</sup> Place</SPAN> Capital One Bank<BR>' + 
'<SPAN class=subtitle1>3<sup>rd</sup> Place</SPAN> Huawei Technologies<BR>' + 
'<SPAN class=subtitle1>4<sup>th</sup> Place</SPAN> PepsiCo \'PAN\'das<BR>' + 
'<SPAN class=subtitle1>5<sup>th</sup> Place</SPAN> Irving Visit-Oars Bureau<BR>' + 
'<DIV class=subtitle2>Women Premier Division</DIV>' + 
'<SPAN class=subtitle1>1<sup>st</sup> Place</SPAN> Art Attack!, Irving Arts Center<BR>' + 
'<DIV class=subtitle2>Men\'s Premier Division</DIV>' + 
'<SPAN class=subtitle1>1<sup>st</sup> Place</SPAN> Hope We Float, Irving Fire Department<BR>' + 
'<SPAN class=subtitle1>2<sup>nd</sup> Place</SPAN> Rock-N-Roll, DFW Technology, Inc<BR>' + 
'<SPAN class=subtitle1>3<sup>rd</sup> Place</SPAN> Taiwan Formosa of Denton<BR>' + 
'<SPAN class=subtitle1>4<sup>th</sup> Place</SPAN> Lee\'s White Leopard Kung Fu School<BR>' + 
'<SPAN class=subtitle1>5<sup>th</sup> Place</SPAN> Atom Smashers<BR>' + 
'<DIV class=subtitle2>Open Division</DIV>' + 
'<SPAN class=subtitle1>1<sup>st</sup> Place</SPAN> Wok n\' Row - Mr. Wok Asian Bistro<BR>' + 
'<SPAN class=subtitle1>2<sup>nd</sup> Place</SPAN> Henry S. Miller<BR>' + 
'<SPAN class=subtitle1>3<sup>rd</sup> Place</SPAN> MedAssets<BR><BR>'; 
