var results2010 = '' +  
'<DIV class=subtitle>2010 Dragon Boat Race Results</DIV>' + 
'<SPAN class=subtitle2>Festival Grand Champion</SPAN> Hope We Float - Irving Fire Department<BR>' + 
'<SPAN class=subtitle1>2<sup>nd</sup> Place</SPAN> Laos & Thal Nam<BR>' + 
'<SPAN class=subtitle1>3<sup>rd</sup> Place</SPAN> The Planet - Dallas<BR>' + 
'<SPAN class=subtitle1>4<sup>th</sup> Place</SPAN> TI Chi - Texas Instruments Chinese Initiative<BR>' + 
'<DIV class=subtitle2>Youth Division - Mixed</DIV>' + 
'<SPAN class=subtitle1>1<sup>st</sup> Place</SPAN> FCC Xiao Dragons - Family with Children from China<BR>' + 
'<DIV class=subtitle2>Youth Division - Men\'s </DIV>' + 
'<SPAN class=subtitle1>1<sup>st</sup> Place</SPAN> Circle Ten Swamp Rats - Boy Scouts<BR>' + 
'<DIV class=subtitle2>Corporate Blue Bonnet Division</DIV>' + 
'<SPAN class=subtitle1>1<sup>st</sup> Place</SPAN> EMJ Corporation - EMJ Corporation<BR>' + 
'<SPAN class=subtitle1>2<sup>nd</sup> Place</SPAN> AT&T/APCA - AT&T<BR>' + 
'<SPAN class=subtitle1>3<sup>rd</sup> Place</SPAN> Kimberly-Clark Corporation<BR>' + 
'<DIV class=subtitle2>Community Division</DIV>' + 
'<SPAN class=subtitle1>1<sup>st</sup> Place</SPAN> DAABA Legal Lions - Dallas Asian American Bar Association<BR>' + 
'<SPAN class=subtitle1>2<sup>nd</sup> Place</SPAN> Up the Creek<BR>' + 
'<SPAN class=subtitle1>3<sup>rd</sup> Place</SPAN> The Oar Mongers<BR>' + 
'<DIV class=subtitle2>Corporate Wildflower Division</DIV>' + 
'<SPAN class=subtitle1>1<sup>st</sup> Place</SPAN> The Planet, Dallas<BR>' + 
'<SPAN class=subtitle1>2<sup>nd</sup> Place</SPAN> TI Chi - Texas Instruments Chinese Initiative<BR>' + 
'<SPAN class=subtitle1>3<sup>rd</sup> Place</SPAN> Hosting Rockstars - The Planet, Houston<BR>' + 
'<DIV class=subtitle2>Cancer Awareness Division</DIV>' + 
'<SPAN class=subtitle1>1<sup>st</sup> Place</SPAN> Mudzilla for Asian Breast Health, Crew 2 - ABHOP<BR>' + 
'<SPAN class=subtitle1>2<sup>nd</sup> Place</SPAN> KOI for Asian Breast Health Outreach - ABHOP<BR>' + 
'<SPAN class=subtitle1>3<sup>rd</sup> Place</SPAN> OCA-DFW - OCA (Organization of Chinese Americans), DFW Chapter<BR>' + 
'<DIV class=subtitle2>Men\'s Premier Division</DIV>' + 
'<SPAN class=subtitle1>1<sup>st</sup> Place</SPAN> Hope We Float, Irving Fire Department<BR>' + 
'<SPAN class=subtitle1>2<sup>nd</sup> Place</SPAN> Laos & Thal Nam - Community team<BR>' + 
'<SPAN class=subtitle1>3<sup>rd</sup> Place</SPAN> Sheriff’s Team - Dallas County Sheriff’s Department<BR>' + 
'<DIV class=subtitle2>Open Division</DIV>' + 
'<SPAN class=subtitle1>1<sup>st</sup> Place</SPAN> Wok n\' Row - Mr. Wok Asian Bistro<BR>' + 
'<SPAN class=subtitle1>2<sup>nd</sup> Place</SPAN> Lee’s White Leopard Kung Fu School<BR>' + 
'<SPAN class=subtitle1>3<sup>rd</sup> Place</SPAN> Team of Confucius Institute - Confucius Institute at UTDallas<BR><BR>'; 
