var results2014 = '' +  
'<DIV class=subtitle>2014 Dragon Boat Race Results</DIV>' +
'<DIV class=subtitle2>Festival Grand Championship Race (Open/Man\'s)</DIV>' +
'<SPAN class=subtitle1>Grand Championship Race (Open/Man\'s)</SPAN> DUC Delite ----	01:07.42<BR>' +
'<SPAN class=subtitle1>2<sup>nd</sup> Place</SPAN>  Boats and Hoses		----		01:07.43<BR>' +
'<SPAN class=subtitle1>3<sup>rd</sup> Place</SPAN>  Austin Coolers		----		01:07.50<BR>' +
'<DIV class=subtitle2>Festival Grand Championship Race (Mixed)</DIV>' + 
'<SPAN class=subtitle1>Grand Champion (Mixed)</SPAN>  JC Penney	----		01:16.46<BR>' + 
'<SPAN class=subtitle1>2<sup>nd</sup> Place</SPAN>  GS Dragons	----		01:17.28<BR>' + 
'<SPAN class=subtitle1>3<sup>rd</sup> Place</SPAN>  OCA Ocean 21 ----		01:17.71<BR>' +
'<DIV class=subtitle2>Open Finals</DIV>' + 
'<SPAN class=subtitle1>1<sup>st</sup> Place</SPAN> DUC Delite ----			01:07.03<BR>' + 
'<SPAN class=subtitle1>2<sup>nd</sup> Place</SPAN> Cajun Invasion ----		01:16.06<BR>' + 
'<SPAN class=subtitle1>3<sup>rd</sup> Place</SPAN> G.E. Capital	----		01:19.18<BR>' + 
'<DIV class=subtitle2>Men\'s Finals</DIV>' +
'<SPAN class=subtitle1>1<sup>st</sup> Place</SPAN> Boats and Hoses ----				01:09.53<BR>' + 
'<SPAN class=subtitle1>2<sup>nd</sup> Place</SPAN> Austin Coolers ----				01:10.27<BR>' + 
'<SPAN class=subtitle1>3<sup>rd</sup> Place</SPAN> DFW Chinese Alliance	----		01:14.07<BR>' + 
'<DIV class=subtitle2>Lantana Finals</DIV>' + 
'<SPAN class=subtitle1>1<sup>st</sup> Place</SPAN> Team AC ----				01:18.12<BR>' + 
'<SPAN class=subtitle1>2<sup>nd</sup> Place</SPAN> OCA Ocean 21	----		01:18.24<BR>' + 
'<SPAN class=subtitle1>3<sup>rd</sup> Place</SPAN> Kung Paos ----			01:27.93<BR>' + 
'<DIV class=subtitle2>Sunflower Finals</DIV>' + 
'<SPAN class=subtitle1>1<sup>st</sup> Place</SPAN> DAABA Legal Lions ----			01:16.56<BR>' + 
'<SPAN class=subtitle1>2<sup>nd</sup> Place</SPAN> Row Row Ratchet ----				01:20.06<BR>' + 
'<SPAN class=subtitle1>3<sup>rd</sup> Place</SPAN> Lee\'s White Leopard	----		01:25.02<BR>' + 
'<DIV class=subtitle2>Blue Bonnet Finals</DIV>' + 
'<SPAN class=subtitle1>1<sup>st</sup> Place</SPAN> JC Penney ----				01:18.09<BR>' + 
'<SPAN class=subtitle1>2<sup>nd</sup> Place</SPAN> Blazing Paddles 3 ----		01:22.71<BR>' + 
'<SPAN class=subtitle1>3<sup>rd</sup> Place</SPAN> HuaWei Wave Runner ----		01:25.80<BR>' + 
'<DIV class=subtitle2>Lavender Finals</DIV>' + 
'<SPAN class=subtitle1>1<sup>st</sup> Place</SPAN> PWC (Aspire)	----			01:23.84<BR>' + 
'<SPAN class=subtitle1>2<sup>nd</sup> Place</SPAN> Blazing Paddles 2 ---		01:26.27<BR>' + 
'<SPAN class=subtitle1>3<sup>rd</sup> Place</SPAN> Aspire ----				01:32.64<BR>' +
'<DIV class=subtitle2>Wildflower Finals</DIV>' + 
'<SPAN class=subtitle1>1<sup>st</sup> Place</SPAN> Celanese	----			01:16.62<BR>' + 
'<SPAN class=subtitle1>2<sup>nd</sup> Place</SPAN> Blazing Paddles 1 ----	01:18.20<BR>' + 
'<SPAN class=subtitle1>3<sup>rd</sup> Place</SPAN> GS Dragons ----			01:19.46<BR>' +
'<DIV class=subtitle2>Youth Division Winner</DIV>' + 
'FCC Dragons<BR>' + 
'<br><br>'
