var release2008 = '' + 
'<DIV class=subtitle style="text-align: center;">Marco Polo World Foundation Announces 2008 Annual DFW Dragon Boat, Kite and Lantern Festival on May 18th</DIV>' + 
'<P>DALLAS &#151; May 7, 2008 - The 2008 Annual DFW Dragon Boat, Kite and Lantern Festival, a premier Asian sporting, cultural and educational event in North Texas, will be held on May 18th at Lake Carolyn, Irving, Texas. Spirited dragon boat races, spectacular kites, traditional dragon and lion dances, dumpling-making demonstrations, and colorful multi-cultural performances will distinguish this year’s action-packed festival.' + 
'With strong support from corporations, community groups, and city governments, the festival was launched with grand fanfare last year. Corporate and community teams raced with great excitement in a first ever sport for the DFW region. Educational, cultural programs were appreciated while several DFW mayors proclaimed the month of May as Asian Pacific Heritage Month.</P>' + 
'' + 
'<P>This year, the co-hosts, Marco Polo World Foundation and ACP Foundation, are pleased to invite the press and the public to the May 18th festival that will be held from 10:00 a.m. to 6:00 p.m. &#145; We are fortunate to have the strong support of Irving City Mayor Herbert Gears, City Council, the Visitor’s Bureau, the Greater Irving Las Colinas Chamber of Commerce and DCURD,&#146; said the festival co-chairs, Diana Meilan Wang and Lily Mak. This volunteer run event is free to the public to attend.</P>' + 
'<P>Under the supervision of the Dragon Boat Association of Texas and USA Dragon Boating organization, the DFW Chapter of the Dragon Boat Association of Texas has introduced new racing categories this year: education and a special race for breast cancer awareness. A Boy Scout troop, high school rowing team, and college team make up the participants in the education division while the breast cancer awareness race features a Susan G. Komen Grantee team and a visiting out-of-town team composed of many breast cancer survivors. Over fifteen dragon boat teams consisting of twenty paddlers each and a drummer, are participating in this year’s event, doubling the number of team entries from last year’s event.</P>' + 
'<P>In addition to the dragon boat races featuring corporate and community teams, there will be a main stage hosting multi-cultural performances as well as numerous booths showcasing handicrafts, educational cultural activities and ethnic food. The festival also highlights kite flying demonstrations by members of the TKO and AKA who are supporting the festival for the first time. &#145The festival is truly a community event that crosses all cultures and ages.&#146</P>' + 
'<P>Dragon Boating is one of the hottest growing sporting events. Such events are already held with great success in Canada, northeast and western United States. Established Dragon Boat programs in Boston, New York and Los Angeles attract close to 50,000 participants each year. China has already recommended the sport to be adopted by the Olympic Committee as an official sport.</P>' + 
'<P>All founding co-hosts of the festival look forward to building the festival as a DFW Regional event that reflects its internationalism and awareness of the cultures of its major trading partners in Asia.</P>' + 
'' + 
'<DIV class=subtitle>About Marco Polo World Foundation (MPWF)</DIV>' + 
'<P>Marco Polo World Foundation initiated the First Annual DFW Dragon Boat, Kite and Lantern Festival in 2007. Its mission is to promote the new sport of Dragon Boating in the DFW region, showcase Asian culture, enhance intercultural understanding and celebrate Asian/Pacific Heritage Month. The Festival also promotes cancer awareness and works with private and public sector partners and community organizations to encourage regional and international participation.</P>' + 
'<P>Visit the festival website at www.dfwdragonboatfestival.com.</P>';
